import Header from '@/components/header';
import Footer from '@/components/footer';
import './globals.css';

export const metadata = {
  title: 'Vixco',
  description: 'Generated by next',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
